# Generated by Django 3.2.7 on 2021-10-24 20:20

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('thumbnail', models.ImageField(blank=True, upload_to=articles.models.path_and_rename, verbose_name='Thumbnail')),
                ('type', models.CharField(choices=[('Games', 'Jogos'), ('Movies', 'Filmes'), ('Series', 'Séries'), ('Books', 'Livros')], max_length=150, verbose_name='Assunto')),
                ('resume', models.CharField(max_length=150, verbose_name='Resumo')),
                ('body', models.TextField(verbose_name='Texto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='Exclusivo')),
                ('author', models.ForeignKey(limit_choices_to={'is_writer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
