version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - blog-django

  db:
    # image: postgres:latest
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_blog_data:/var/lib/postgresql/data/
    networks:
      - blog-django
    # ports:
    # - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin4"
    ports:
      - 15432:80
    depends_on:
      - db
    networks:
      - blog-django
    
volumes:
  postgres_blog_data:

networks:
  blog-django:
    driver: bridge
